theme: jekyll-theme-minimal
title: "Android : Beginner Projects"
logo: "https://avatars1.githubusercontent.com/u/48084596?s=460&u=4d74282b07803dda9d1eb7f19c0a7da14a7a65a2&v=4"
show_downloads: "https://github.com/shobhit24/android-beginner-projects/archive/master.zip" 
